### ISSUE TITLE
Use Crashlytics NDK support

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2107]
It seems that Crashlytics has NDK support: http://docs.fabric.io/android/crashlytics/ndk.html

**Comment by ljbade** [comment]
Taking this on.

From the doc it seems we need to:
- [ ] add the aar to the project
- [ ] get symbol uploading to work

**Comment by ljbade** [comment]
Work in https://github.com/mapbox/mapbox-gl-native/tree/2107-crashlytics-ndk

**Comment by ljbade** [comment]
Got it loading:
```
09-18 10:06:11.341  12522-12522/com.mapbox.mapboxgl.testapp D/libcrashlytics﹕ Initializing libcrashlytics version 1.1.1
09-18 10:06:11.341  12522-12522/com.mapbox.mapboxgl.testapp D/libcrashlytics﹕ Attempting to load unwinder...
09-18 10:06:11.341  12522-12522/com.mapbox.mapboxgl.testapp D/libcrashlytics﹕ Done; using libunwind
09-18 10:06:11.341  12522-12522/com.mapbox.mapboxgl.testapp D/libcrashlytics﹕ Attempting to register signal handler...
09-18 10:06:11.341  12522-12522/com.mapbox.mapboxgl.testapp D/libcrashlytics﹕ Signal handler registered.
09-18 10:06:11.341  12522-12522/com.mapbox.mapboxgl.testapp D/libcrashlytics﹕ Initializing native crash handling successful.
09-18 10:06:11.341  12522-12522/com.mapbox.mapboxgl.testapp I/CrashlyticsCore﹕ Initializing Crashlytics 2.3.4.74
```

**Comment by ljbade** [comment]
Time to crash

**Comment by ljbade** [comment]
Useful info at https://fabric.io/downloads/gradle (enable the NDK switch at the top).

Says to run `./gradlew crashlyticsUploadSymbolsRelease` after you publish any builds. I think we could integrate this into our build scripts (or in gradle file).

@bleege ^

**Comment by ljbade** [comment]
Also says to add:
```
crashlytics {
enableNdk true
androidNdkOut 'src/main/obj'
androidNdkLibsOut 'src/main/libs'
}
```

**Comment by ljbade** [comment]
Hmm I get this when I run the gradle command:
`Task 'crashlyticsUploadSymbolsRelease' not found in root project 'java'.`

**Comment by ljbade** [comment]
After the crashlytics block to build.gradle I now get:
```
ERROR - Crashlytics Developer Tools error.
com.crashlytics.tools.android.project.codemapping.CodeMappingException: Crashlytics could not find NDK output directory '/home/leith/mb/mapbox-gl-native/android/java/MapboxGLAndroidSDKTestApp/src/main/obj'. Is the -androidNdkOut setting configured correctly?
```

**Comment by ljbade** [comment]
After the crashlytics block to build.gradle I now get:
```
ERROR - Crashlytics Developer Tools error.
com.crashlytics.tools.android.project.codemapping.CodeMappingException: Crashlytics could not find NDK output directory '/home/leith/mb/mapbox-gl-native/android/java/MapboxGLAndroidSDKTestApp/src/main/obj'. Is the -androidNdkOut setting configured correctly?

**Comment by ljbade** [comment]
Hmm I fixed up the paths:
```
crashlytics {
    enableNdk true
    androidNdkOut '../../../build/android-arm-v7/Release/obj.target'// TODO detect release/debug? or maybe get gyp to debug lib to obj folder
    androidNdkLibsOut '../../../build/android-arm-v7/Release/lib.target'
}
```

But now I get:
```
java.io.FileNotFoundException: /home/leith/mb/mapbox-gl-native/build/android-arm-v7/Release/lib.target/gyp/libmapbox-gl.so was not found. Is the -androidNdkLibsOut setting configured correctly?
```

I have no idea where the extra `/gyp` in the path is from.

**Comment by ljbade** [comment]
For some reason this worked:
```
crashlytics {
    enableNdk true
    androidNdkOut '../../../build/android-arm-v7/Release/obj.target'
    androidNdkLibsOut '../../../build/android-arm-v7/Release/obj.target'
}
```

**Comment by ljbade** [comment]
Now I need it to configure the `Release` bit automatically somehow

**Comment by ljbade** [comment]
or perhaps copy that folder

**Comment by ljbade** [comment]
Trying to copy the `build/android-arm-v7/Release/obj.target` directory contents to `android/java/MapboxGLAndroidSDK/src/main/obj` so we are compatible with `ndk-build` locations, but having trouble with the gyp.

So far this:


Gives me this error:
```
/bin/sh: 1: builddir: not found
ls: cannot access /obj.target/*: No such file or directory
gyp: Call to 'ls -1 $(builddir)/obj.target/*' returned exit status 2.
scripts/main.mk:83: recipe for target 'Makefile/__project__' failed
make[1]: *** [Makefile/__project__] Error 1
make[1]: Leaving directory '/home/leith/mb/mapbox-gl-native'
Makefile:71: recipe for target 'android-lib' failed
make: *** [android-lib] Error 2
```

I was trying to use the wild card trick from http://stackoverflow.com/a/32136063

I had tried this before:
```
        {
        'files': [
          '<(PRODUCT_DIR)/obj.target'
        ],
        'destination': '<(pwd)/../android/java/MapboxGLAndroidSDK/src/main/obj'
        },
```

But it copies the `obj.target` *inside* `obj` like: `android/java/MapboxGLAndroidSDK/src/main/obj/obj.target` instead of the contents.

@kkaefer Can you help me with ^

**Comment by bleege** [comment]
Great start @ljbade!  :+1:

**Comment by bleege** [comment]
Oh, btw... the short term purpose for this work is to aid in solving #2295 and #1941 .

**Comment by ljbade** [comment]
@bleege @incanus Can you try this branch?

After building with `make android` you then run `./gradlew crashlyticsUploadSymbolsRelease`

I need to check though if uploading symbols from a MBGL snapshot will cause the symbols to be loaded for Sirius crashes (when we implement it there) since Sirius does not have access to a copy of the unstripped symbols.

**Comment by bleege** [comment]
@ljbade I'm building a new SNAPSHOT based off `2107-crashlytics-ndk` now and will then run `./gradlew crashlyticsUploadSymbolsRelease`.

**Comment by bleege** [comment]
I just pushed SNAPSHOT 21 to Maven Central.  My process was below, with all commands executing successfully:

```sh
make aproject
cd android/java
// Update MapboxGLAndroidSDK/gradle.properties with credentials
./gradlew uploadArchives
./gradlew crashlyticsUploadSymbolsRelease
```

**Comment by bleege** [comment]
Reopening because of a [small implementation issue](https://github.com/mapbox/mapbox-gl-native/commit/db6a08d8caef8818032a89725340419f258d09ea#commitcomment-13397592) where the generated `.so` are placed in `libs` and not in `jniLibs` which is causing the SDK to not work at run time.

**Comment by bleege** [comment]
Related to https://github.com/mapbox/mapbox-gl-native/issues/2401

**Comment by ljbade** [comment]
Putting everything in here:

@bleege Actually I think I found this too last night but fell asleep before I committed it. Basically in build.gradle remove the `universalApk true` line.

@bleege ~~Apparently `libs` is now the expected place for NDK binaries in Android Studio, and `jniLibs` is the legacy location that still gets checked.~~'

I found screenshots of Android Studio still with `jniLibs`.

I'll make a PR that changes back to `jniLibs` and disables universal APK.

**Comment by ljbade** [comment]
Fixed in PR #2404

**Comment by bleege** [comment]
Reopening due to issues described in #2401, specifically https://github.com/mapbox/mapbox-gl-native/issues/2401#issuecomment-142974824.

Moving this `0.2.0` as we should be past need for it in `0.1.0` now.

**Comment by bleege** [comment]
Porting definition of success over from https://github.com/mapbox/mapbox-gl-native/issues/2401#issuecomment-142974824

In order for this to be consider successfully implemented the following need to occur:

1. Checkout `master`
1. Run `make clean`
1. Run `make android`
1. Run TestApp in Device without Stacktraces like [previously noted](https://github.com/mapbox/mapbox-gl-native/issues/2401#issue-107975114) above occurring.

**Comment by ljbade** [comment]
Main issue is that Crashlytics NDK AAR they provide via Maven has 64bit support, while Mapbox GL does not support 64bit.

Solutions:
- roll a custom AAR that removes 64bit and include in repo (ugly)
- get Crashlytics to upload a 32bit only AAR to Maven
- get ARM64 support working (unlikely until next NDK release) - https://github.com/mapbox/mapbox-gl-native/issues/1956

**Comment by bleege** [comment]
> while Mapbox GL does not support 64bit.

We should be _very specific about this_... Mapbox GL does run on 64 bit devices.  What you're referring to is that the `.aar` doesn't contain an `arm64` ABI `.so`.  It does contain a 32bit `arm` ABI.  For more information people should see the discussion at https://github.com/mapbox/mapbox-gl-native/issues/1956#issuecomment-137496217.
