### ISSUE TITLE
[Android] Annotation do not open info when clicked

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#3584]
I've been trying to [debug this issue](https://github.com/mapbox/react-native-mapbox-gl/issues/102) now in react-native land for a while. Symptoms:

* Touching an annotation marker does not open the infowindow
* However, I can log events  with `setOnMarkerClickListener`. The event fires but there is no infowindow
* When rotating the map, if the annotation was clicked, the info window appears
* When rotating back upright, the infowindow is displayed when clicked normally
* (Also, the map becomes very distorted when rotated, this can be handled in another ticket) 

I'm not certain if this is a react native bug or a gl-native bug. Perhaps react is clobbering touch events on initial load? 

/cc @brentvatne @tobrun @zugaldia @bleege 

![](https://cldup.com/rQpDPUoUNw.gif)

**Comment by bsudekum** [comment]
Marker annotations are added here https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/src/main/java/com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLManager.java#L157

**Comment by tobrun** [comment]
Linking https://github.com/mapbox/mapbox-gl-native/issues/3573.

**Comment by tobrun** [comment]
This should be resolved when #3573 lands. 
Notice that this will be merged to the `release branch of 3.1.0` and not on master.

**Comment by tobrun** [comment]
Landed with 74a9c50 on release branch of 3.1.0 in #3537.

**Comment by tobrun** [comment]
@bsudekum also happy to report that #3156 will land with release of 3.1.0. 
The related PR has some great improvements for touch handling on Android.

**Comment by bsudekum** [comment]
@tobrun - @bleege put out a snapshot that included this fix. After testing, I'm still seeing that I cannot open marker annotations on the initial load without rotating the map first.

**Comment by bleege** [comment]
Just noting that the SNAPSHOT with the fix is https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-sdk/3.1.0-SNAPSHOT/mapbox-android-sdk-3.1.0-20160119.193839-22.aar and it's based on the latest code in `release-android-v3.1.0` branch.

**Comment by tobrun** [comment]
@bsudekum now by properly reading through your use-case I think the source of your problem can be found downstream rather than upstream. I have never saw this behaviour on Android GL before. I will do some debugging in react when I'm picking up https://github.com/mapbox/react-native-mapbox-gl/issues/249

**Comment by tobrun** [comment]
@bsudekum 
I wanted to take a look at this issue by debugging react-native, but I'm having trouble finding documentation for setting up my development environment to contribute to react-native. I have created this issue for https://github.com/mapbox/react-native-mapbox-gl/issues/252.

**Comment by zugaldia** [comment]
@bsudekum I see that on Android `react-native-mapbox-gl` does not include the required [activity lifecycle methods](https://www.mapbox.com/android-sdk/#lifecycle_methods).

From looking at the React Native docs, it seems there're two possible ways to fix this, both within the `ReactNativeMapboxGLModule` class. Could you check if either of them help with this issue? (I'm sorry, I don't have a working React Native set up at the moment).

Option 1: Via the `Application` object.

```
getCurrentActivity().getApplication().registerActivityLifecycleCallbacks(new Application.ActivityLifecycleCallbacks() {
    @Override
    public void onActivityCreated(Activity activity, Bundle savedInstanceState) {
        aPackage.getManager().getMapView().onCreate(savedInstanceState);
    }

    @Override
    public void onActivityStarted(Activity activity) {
        // see onActivityCreated
    }

    @Override
    public void onActivityResumed(Activity activity) {
        // see onActivityCreated
    }

    @Override
    public void onActivityPaused(Activity activity) {
        // see onActivityCreated
    }

    @Override
    public void onActivityStopped(Activity activity) {
        // see onActivityCreated
    }

    @Override
    public void onActivitySaveInstanceState(Activity activity, Bundle outState) {
        // see onActivityCreated
    }

    @Override
    public void onActivityDestroyed(Activity activity) {
        // see onActivityCreated
    }
});
```

Option 2: Via the `addLifecycleEventListener` method.

```
reactContext.addLifecycleEventListener(new LifecycleEventListener() {
    @Override
    public void onHostResume() {
        aPackage.getManager().getMapView().onResume();
    }

    @Override
    public void onHostPause() {
        // see onHostResume
    }

    @Override
    public void onHostDestroy() {
        // see onHostResume
    }
});
```

Option 1 seems to be the better option as it includes the full cycle, not just a subset of it. Either way, I believe we should leave one of them in the code as not including these methods is a common source of errors in the SDK.

/cc: @bleege @tobrun

**Comment by bsudekum** [comment]
Option 2 gives the following error:

```
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React: Exception in native call from JS
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.views.MapView.onResume()' on a null object reference
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLModule$1.onHostResume(ReactNativeMapboxGLModule.java:37)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at com.facebook.react.bridge.ReactContext.onResume(ReactContext.java:140)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at com.facebook.react.ReactInstanceManagerImpl.moveReactContextToCurrentLifecycleState(ReactInstanceManagerImpl.java:761)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at com.facebook.react.ReactInstanceManagerImpl.setupReactContext(ReactInstanceManagerImpl.java:599)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:84)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:187)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:162)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at android.os.AsyncTask.finish(AsyncTask.java:632)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at android.os.AsyncTask.access$600(AsyncTask.java:177)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at android.os.Looper.loop(Looper.java:135)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at android.app.ActivityThread.main(ActivityThread.java:5292)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at java.lang.reflect.Method.invoke(Native Method)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at java.lang.reflect.Method.invoke(Method.java:372)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
02-11 07:42:51.013 6937-6937/com.testbed E/unknown:React:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by tobrun** [comment]
Closing this issue as this is an downstream issue in react-native rather than an Android SDK one.
