### ISSUE TITLE
[android] onMapReady not called in offline mode (for non mapbox:// styles)

### ISSUE THREAD

**Issue by erikandre** [mapbox/mapbox-gl-native#4393]
SDK: Latest 4.0.0 SNAPSHOT build (as of March 18th)
[log.txt](https://github.com/mapbox/mapbox-gl-native/files/180522/log.txt)

**Steps to reproduce**

(the attached log covers step 3-4)

1. Load map with style from http://*.json address
2. Kill app
3. Enable airplane mode
4. Reopen app

**Expected result**

Map is displayed based on cached and offline data. onMapReady() callback method is invoked.

**Actual result**

No map is displayed, onMapReady() callback method is not invoked until network becomes available.

**Other info**

When using one of the predefined mapbox://... styles I get the expected result (being able to show something even with no network connection and callback being invoked).

**Comment by jfirebaugh** [comment]
To clarify -- have you explicitly created an offline region for the `http://`-based style, or are you expecting it to be cached for other reasons?

**Comment by erikandre** [comment]
@jfirebaugh Yes, I get this behaviour both when I have offline regions (which have finished downloading) and when I don't.

Even with no offline regions added I was hoping that the style would be cached but that was just based on the behaviour I observed when trying the same with the predefined styles.

**Comment by erikandre** [comment]
Even though I never get the onMapReady callback there does seem to be some data loaded at least.
When I zoom in and out I very briefly see parts of the map and the background color is also the one I've specified in the style.

**Comment by tobrun** [comment]
FWIW
The android `onMapReady` callback is called when we receive `DID_FINISH_LOADING` event.
The `DID_FINISH_LOADING` is triggered when render state is ` RenderState::fully` and data is loaded.:

```cpp
void Map::renderSync() {
    ....
   } else if (renderState != RenderState::fully) {
        renderState = RenderState::fully;
        view.notifyMapChange(MapChangeDidFinishRenderingMapFullyRendered);
        if (data->loading) {
            data->loading = false;
            view.notifyMapChange(MapChangeDidFinishLoadingMap);
        }
    }
    ....
}
``` 

Will need to do dig deeper into this and do some tests.

**Comment by tobrun** [comment]
@jfirebaugh is waiting for `view.notifyMapChange(MapChangeDidFinishLoadingMap);` event not correct when taking in account caching and offline?

**Comment by jfirebaugh** [comment]
@erikandre  The `beta.1` release had a bug that prevented offline regions from being used after downloading. This was fixed for `beta.2`, released today, and I would now expect the behavior in the case where you have an offline region to be as you expect.

In the case where there is not an offline region present, the SDK does do some caching based on ambient use patterns, but makes no guarantee that you'll be able to obtain a complete load of the map if network access is not available, even if you've previously viewed the same style in the same area. If you need that guarantee, create an offline region.

**Comment by erikandre** [comment]
@jfirebaugh Great! I will try to verify this later today. Thanks

**Comment by tobrun** [comment]
@erikandre how are you adding the Map?
 - Layout file
 - MapFragment
 - Programatically

I noticed that the callback is only invoked when you pan/zoom the map for the 2 last ones. https://github.com/mapbox/mapbox-gl-native/issues/4439

**Comment by erikandre** [comment]
@tobrun I've got a fragment that extends SupportMapFragment that I add programatically.

I've retested this on the 4.0.0beta2 build but I'm still getting the same behaviour. I tried panning zooming as you suggested but even though I sometimes see (very briefly) parts of the map being drawn and then erased I'm not getting the callback.

I've downloaded an offline area that should cover the view that the map is initially showing so I should have all the data needed I think.

**Comment by tobrun** [comment]
It could be true that the combination of having offline ignores the pan/zoom fix I'm referring to (because it's not triggering loading of new content). Need to investigate what is going wrong. For now you could try working around this by using a MapView in your Activity that is inflated through xml.

**Comment by tobrun** [comment]
I'm not thinking that above mentioned issue by me (on master) is not the same as the one mentioned here (on release branch). To reproduce this on the testapp I'm converting the OfflineActivity to a SupportMapFragment approach. This should give us the same results as mentioned in this issue and #4438.

**Comment by tobrun** [comment]
The result after porting is visible [here](https://www.dropbox.com/s/378tnzkyz0nxu6l/device-2016-03-24-101534.mp4?dl=0) and code is [here](https://gist.github.com/tobrun/9e6fc7ed17ec8b443c4b).

**Comment by vfaSonnt** [comment]
I don't think it is related to offline function but fragment problem. I test only with SupportMapFragmentActivity, not OfflineActivity. Network on, it animate Camera, without network , it stay still.
```
mapFragment.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(@NonNull MapboxMap mapboxMap) {
                Log.d(TAG, "Map is ready");
                mapboxMap.animateCamera(CameraUpdateFactory.zoomBy(2), 3500);
            }
        });
```

**Comment by tobrun** [comment]
@vfaSonnt I replied to your issue [here](https://github.com/mapbox/mapbox-gl-native/issues/4438#issuecomment-200752038).

**Comment by NamtarR** [comment]
I have run into the issue today with the following code both on 4.0.0-rc1 and 4.0.0-SNAPSHOT. Also it seems that I have bumped in this even with mapbox://-style, since I use predefined styles for now.

```java
    mMapView.setStyleUrl(Style.MAPBOX_STREETS);
    mMapView.getMapAsync(new OnMapReadyCallback() {
    @Override
    public void onMapReady(@NonNull MapboxMap mapboxMap) {
                    mMapboxMap = mapboxMap;
                    mWhiteScreen.setVisibility(View.GONE);
                    mProgress.setVisibility(View.GONE);
                    setupMapView();
            }
    });
```

The mapView in my app is in my custom map fragment and inflated from layout file. The Offline region with style Style.MAPBOX_STREETS is already downloaded, but no luck - the app is trying to reach api.mapbox.com.

**Comment by zugaldia** [comment]
@NamtarR could you please check if you're seeing the same behavior described in https://github.com/mapbox/mapbox-gl-native/issues/4500?

**Comment by tobrun** [comment]
I believe the fix for https://github.com/mapbox/mapbox-gl-native/issues/4500 will resolve this

**Comment by NamtarR** [comment]
@zugaldia Okay, I have tried this with different areas downloaded.
To tell the truth offline regions are really strange and I don't understand what makes them so large.
Anyway, the initial size of my app's data with the region I need already downloaded was 78.34 megabytes and the map was not loading. Now I have tried the region 4 times smaller, the app downloaded half as much resources and the data size became 72.2 megabytes. The issue is still there.

**Comment by Fintasys** [comment]
For me onMapReady still not get called while I'm offline and opening the app. I'm using Mapbox Android SDK 4.0.1. Shouldn't it have been fixed?

**Comment by tobrun** [comment]
@Fintasys the `4.0.1` contains a fix for an annotations issue, the offline issue is fixed on master and can be verified using the 4.1.0-SNAPSHOT. installation instructions are [here](https://www.mapbox.com/android-sdk/#gradle).

**Comment by Fintasys** [comment]
@tobrun thx ! last time I tried the snapshot it didn't worked. But now it's working great!
