### ISSUE TITLE
Annotations not stable or disappear after loop

### ISSUE THREAD

**Issue by zhemora** [mapbox/mapbox-gl-native#5019]
**Platform: Samsung Note 3 - Android Lollipop 5.0**
**Mapbox SDK version: 4.1.0-SNAPSHOT**

### Steps to trigger behavior

 1. After we rebuild last update the MapBox SDK 4.1.0-SNAPSHOT, then the problem is occur.
 2. Marker or annotation not stable, sometimes it show or hide from map.

**Comment by tobrun** [comment]
@zhemora could you verify it's the `4.1.0-SNAPSHOT` dependency? 
The problem now is that there are multiple versions at this time:
 - 4.0.1-SNAPSHOT
 - 4.0.1
 - 4.1.0-SNAPSHOT (this one hasn't been build for a couple of days)

And I need to be sure before looking into where the problem is originating from.

I just kicked of a build for the `4.1.0-SNAPSHOT` so it reflects the latest state of master.

**Comment by zhemora** [comment]
@tobrun i use 4.1.0-SNAPSHOT, previously not problem with 4.1.0-SNAPSHOT.

![image](https://cloud.githubusercontent.com/assets/4024378/15240476/16044dec-1914-11e6-8e44-6f68c404fb28.png)

The problem is, when we create marker by looping the data position, and then we clear the map by "removeAnnotations()" and recreate marker again with the same data, we see the markers is gone.

![image](https://cloud.githubusercontent.com/assets/4024378/15240787/305d9b24-1916-11e6-8c2f-d236cb2398f7.png)

![image](https://cloud.githubusercontent.com/assets/4024378/15240795/3e54bdde-1916-11e6-9800-1c04b5913fd5.png)

Thanks for your help.

**Comment by tobrun** [comment]
@zhemora 
To investigate this issue I created some sample code in 14e1207. 
The code adds/removes markers to/from a map constantly every 1500ms. 

![ezgif com-video-to-gif 11](https://cloud.githubusercontent.com/assets/2151639/15243178/5c4c98b4-18fa-11e6-83d0-f5936e28eef6.gif)

Could you share some code how you are adding/removing these markers? or compare it with 14e1207? Could you try testing with the newer SNAPSHOT? (for this you need to invalidate gradle caches and do a gradle sync)

**Comment by zhemora** [comment]
@tobrun if we use default marker icon no problems occur, but if we use marker with custom icon and large (500) data position then the problem is occur (with newer SNAPSHOT). Thanks.

**Comment by tobrun** [comment]
@zhemora thank you for adding that information. Will try to reproduce.

**Comment by zhemora** [comment]
@tobrun fyi, 

**Platform: Samsung Note 3 - Android Lollipop 5.0
Mapbox SDK version: Newer Sync 4.1.0-SNAPSHOT**

1) Sample code for adding/removing markers :

![image](https://cloud.githubusercontent.com/assets/4024378/15252936/3cf77ea6-195a-11e6-8bd8-55b76ea034ad.png)

2) Showing the issue :

![2016_05_13_22_11_25_1463152442350_videotoimagegif](https://cloud.githubusercontent.com/assets/4024378/15253089/dc9d4ae4-195a-11e6-806b-4d4b98017491.gif)

Thanks for your help.

**Comment by tobrun** [comment]
@zhemora thank you for adding the code and GIF demonstrating the issue. 
Going to reproduce locally and debug why the markers aren't reloaded.

**Comment by tobrun** [comment]
No problems doing a couple of iterations -> 2399 id marker
![device-2016-05-17-110341](https://cloud.githubusercontent.com/assets/2151639/15316833/0f894bc6-1c1f-11e6-9639-c5c1900a6ebb.png)

Next iteration I'm seeing some markers not being added to the map -> 2999 id latest maker

![device-2016-05-17-110552](https://cloud.githubusercontent.com/assets/2151639/15316902/57364bae-1c1f-11e6-84d6-71977c7b7ce5.png)

Next iteration, no markers shown -> 3599 id latest marker

![device-2016-05-17-110749](https://cloud.githubusercontent.com/assets/2151639/15316952/a0c1ae76-1c1f-11e6-80e2-4d392cc1d7a5.png)

@1ec5 are you seeing the same on iOS? Any id what the cause of this could be?

**Comment by tobrun** [comment]
@zhemora a workaround for now is to manage the markers yourself. So instead of adding/removing them constantly. I would suggest updating the position by calling `setPosition` by iterating over the newly received data and comparing this with the old data.

**Comment by Schumi09** [comment]
Your example matches those observations I have described in the comments of #4778. It happens only   if you create new icons for every iteration from resources. I guess if you change your example to make use of an Icon that you always reuse this issue won't appear. However, for my use case i need to create new icons for every itereation as i need to change alpha and orientation (depending of the location of an off screen object).

**Comment by tobrun** [comment]
Thank you @Schumi09 for that remark. It's starting to come back to me and I'm guessing this is related to the limitation of our sprite atlas being 1024x1024. More information about this issue can be found in https://github.com/mapbox/mapbox-gl-native/issues/3185.

**Comment by afathman** [comment]
I have a similar issue on 4.0.0, removeAnnotations doesn't remove any custom markers.

**Comment by tobrun** [comment]
@aftahman that issue should be fixed with 4.0.1

**Comment by afathman** [comment]
Ah, didn't notice the update. Thanks!

**Comment by Schumi09** [comment]
> Thank you @Schumi09 for that remark. It's starting to come back to me and I'm guessing this is related to the limitation of our sprite atlas being 1024x1024. More information about this issue can be found in #3185. I'm going to do some tests around this to find the best way to handle this for now and will be closing this issue in favour of #3185. FWIW #3276 in combination with #4693 will make the use-case possible and will not limit us changing the marker.

So as the the current state for the 4.1.0 snapshot brought the nice MarkerViews I have replaced the Marker in my project that caused this issue for me with a MarkerView. After several minutes I can still see the MarkerViews. I guess it is save to confirm that your work has fixed this indeed :+1:

**Comment by tobrun** [comment]
@Schumi09 thanks for validating, going to close this for now since we have the MarkerView workaround.

**Comment by Emeritus-DarranKelinske** [comment]
Can you please re-open this? Even though there is a workaround the intended/expected functionality does not work.

**Comment by dazza5000** [comment]
Our current testing shows that switching to MarkerViews is a valid workaround.

**Comment by tobrun** [comment]
@Emeritus-DarranKelinske I would advice you to look into runtime styling. We are finalising this feature for the 4.2.0 release. These API supports the concept of SymbolLayer which is simaler to what Marker use in the low level API.
