### ISSUE TITLE
fillColorForPolygonAnnotation not handling alpha as expected

### ISSUE THREAD

**Issue by kehlawler** [mapbox/mapbox-gl-native#7524]
In Version 3.3 of the iOS mapbox SDK one had to react to delegate methods fillColourForPolygonAnnotation and alphaForShapeAnnotation to get the colour/alpha wanted for a polygon.  I have a circle polygon with the colour rgba = 0, .75, 1.0, 0.1.   In 3.3 I would return rgba colour = (0, .75, 1.0, 1.0) for the fillColourForPolygonAnnotation delegate and 0.1 for the alphaForShapeAnnotation delegate resulting in alphaOld.png (see 1st screenshot below).

In Version 3.4 alphaForShapeAnnotation has been deprecated and the alpha supposedly handled with the fillColour only.  I therefore now simply return colour rgba  = 0, .75, 1.0, 0.1 in fillColourForPolygonAnnotation only (The method alphaForShapeAnnotation has been disabled in my code).  The result is not the same colour as previously obtained (see 2nd screenshot below). 

All other mapping api's I use (mapkit, arcGIS) produce the desired colour depicted in alphaold.png using the same colour components.

**Platform:** iOS
**Mapbox SDK version:** 3.4 beta 5

### Steps to trigger behavior

 1. Create a polygon annotation with colour r = 0, g = .75, b = 1.0, a = 0.1

### Expected behavior
Colour as depicted in screen shot alphaOld.png
![alphaold](https://cloud.githubusercontent.com/assets/8228577/21439271/e28b9f6e-c841-11e6-9a07-6f5792d26854.png)

### Actual behavior
Colour as depicted in screen shot alphaNew.png
![alphanew](https://cloud.githubusercontent.com/assets/8228577/21439275/e9353a50-c841-11e6-9bf7-4ae94e067fc6.png)

**Comment by friedbunny** [comment]
It looks like the blending is wrong, though I’m unsure why that would be the case. The deprecation happened in https://github.com/mapbox/mapbox-gl-native/pull/6706.

In the meantime, staying with the old `alphaForShapeAnnotation:` delegate method should be a viable workaround, if this is indeed related to the deprecation.

**Comment by kehlawler** [comment]
Yes, doing things as I did before works just fine.

**Comment by 1ec5** [comment]
Putting this on the v3.4.0 milestone because we’re leading developers to this bug by deprecating the old API.

**Comment by 1ec5** [comment]
`-[MGLPolygon annotationObjectWithDelegate:]` sets the annotation’s `opacity` to the result of `-[MGLMapView alphaForShapeAnnotation:]` and the annotation’s `color` to the result of `-[MGLMapView fillColorForPolygonAnnotation:]` (which now includes the alpha component). In the absence of an `-[MGLMapViewDelegate mapView:alphaForShapeAnnotation:]` implementation, `-[MGLMapView alphaForShapeAnnotation:]` itself calls `-[MGLMapView fillColorForPolygonAnnotation:]` to determine the alpha; therefore, the alpha components specified by `-[MGLMapViewDelegate mapView:strokeColorForShapeAnnotation:]` and `-[MGLMapViewDelegate mapView:fillColorForPolygonAnnotation:]` are factored in twice.

I also wonder whether it made sense to deprecate `-[MGLMapViewDelegate mapView:alphaForShapeAnnotation:]` in the first place, since it maps directly to the `fill-opacity` and `line-opacity` paint properties under the hood, which aren’t going away.

**Comment by 1ec5** [comment]
* [ ] Fix this regression by reverting the changes to `-[MGLMapViewDelegate mapView:alphaForShapeAnnotation:]` in #6706
* [ ] Undeprecate `-[MGLMapViewDelegate mapView:alphaForShapeAnnotation:]` to allow the developer to control both the opacity of the overall shape and the opacity of the fill or stroke individually

**Comment by friedbunny** [comment]
Fixed by #7710 in the `release-ios-v3.4.0` branch.

**Comment by jlubeck** [comment]
This doesn´t seem to be fixed... That pull request seems to removes the deprecation of  `-[MGLMapViewDelegate mapView:alphaForShapeAnnotation:]` but the problem of the issue itself (changing the alpha `onfillColourForPolygonAnnotation` ) is still broken and makes the fill an opaque white when using alpha different than 1
